### ISSUE TITLE
cmdline program for URL transformation

### ISSUE THREAD

**Issue by v217** [forestrf/Descargavideos#7]
_Thank you for this great website, especially for people with slow internet connections!_

Is it possible to run url transformation without the server?
E.g.:
```bash
descargavideos url
# with the output:
download_url
```

**Comment by forestrf** [comment]
You will need to rewrite some php. The code is ugly, most of it was made while I was learning to program, so I just made it work for this web.
Some time ago I tried to make an API for it, but it didn't work because some websites required running some javascript to make requests from the client side, as the videos could only be served to the IP that requested them, which wouldn't be a problem if you were running the code in your own computer but that wasn't the case, and so the API was ditched.

**Comment by v217** [comment]
So I will stick to the website.
Thanks for the fast reply, if that's ok, I will close the issue.
